Controllers/FuzzingLaunchController.cs
using System.Diagnostics;
using ApSafeFuzz.Data;
using ApSafeFuzz.Models;
using ApSafeFuzz.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Renci.SshNet.Common;

namespace ApSafeFuzz.Controllers;

public class FuzzingLaunchController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly ILogger<FuzzingLaunchController> _logger;
    private readonly IOptions<UploadFileSettingsModel> _uploadFileSettings;
    private readonly IConfiguration _configuration;
    private const long MaxFileSize = 10L * 1024L * 1024L * 1024L;

    public FuzzingLaunchController(
        ApplicationDbContext context,
        IOptions<UploadFileSettingsModel> uploadFileSettings,
        IConfiguration configuration,
        ILogger<FuzzingLaunchController> logger)
    {
        _context = context;
        _uploadFileSettings = uploadFileSettings;
        _configuration = configuration;
        _logger = logger;
    }
    
    [Authorize]
    public IActionResult Index()
    {
        ViewBag.buildsCount = _context.UploadFileSettings.ToList().Count;
        ViewBag.fuzzingTasks = _context.FuzzingTasks.ToList();
        return View("Index");
    }

    [Authorize]
    [HttpGet]
    public IActionResult Upload()
    {
        List<UploadFileSettingsModel> buildsOptions = _context.UploadFileSettings.ToList();
        return View("Upload", buildsOptions);
    }
    
    [Authorize]
    [HttpPost]
    [RequestSizeLimit(MaxFileSize)]
    [RequestFormLimits(MultipartBodyLengthLimit = MaxFileSize)]
    public async Task<IActionResult> Upload(IFormFile uploadedFile)
    {
        _logger.LogDebug($"User {HttpContext.User.Identity?.Name} is uploading a file");
        if (uploadedFile == null || uploadedFile.Length == 0)
        {
            _logger.LogError("Empty file");
            return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        _uploadFileSettings.Value.UploadName = uploadedFile.FileName;
        _uploadFileSettings.Value.UploadTime = DateTime.Now;
        _uploadFileSettings.Value.Owner = HttpContext.User.Identity?.Name;
        _uploadFileSettings.Value.InternalName = $"{Guid.NewGuid()}{FileHelper.GetExtension(uploadedFile.FileName)}";
        
        var filePath = Path.Combine(_uploadFileSettings.Value.FilePath, _uploadFileSettings.Value.InternalName);
        _logger.LogDebug($"Saving file: {filePath}");
        await using (var stream = new FileStream(filePath, FileMode.Create))
        {
            await uploadedFile.CopyToAsync(stream);
        }
        _logger.LogInformation($"File saved: {filePath}");
        await _context.UploadFileSettings.AddAsync(_uploadFileSettings.Value);
        await _context.SaveChangesAsync();
        return RedirectToAction("Index");
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> Delete(int fileId)
    {
        _logger.LogDebug($"Deleting file with id {fileId}");
        UploadFileSettingsModel? fileToDelete = await _context.UploadFileSettings.FindAsync(fileId);
        if (fileToDelete == null)
        {
            _logger.LogError($"File with id {fileId} not found");
            return View("Error",
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        string filePath = Path.Combine(fileToDelete.FilePath, fileToDelete.InternalName);
        int result = FileHelper.DeleteFile(filePath);
        switch (result)
        {
            case 0:
                _logger.LogDebug($"File ({fileToDelete.Id}/{fileToDelete.InternalName}) was deleted from disk");
                break;
            case 1:
                _logger.LogWarning($"File ({fileToDelete.Id}/{fileToDelete.InternalName}) does not exist");
                return View("Error",
                    new ErrorViewModel
                    {
                        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                        ErrorMessage = "FIle does not exist"
                    });
            case 2:
                _logger.LogError(
                    $"File ({fileToDelete.Id}/{fileToDelete.InternalName}): error while deleting from disk");
                return View("Error",
                    new ErrorViewModel
                    {
                        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, ErrorMessage = "Unknown error"
                    });
        }
        _context.UploadFileSettings.Remove(fileToDelete);
        await _context.SaveChangesAsync();
        _logger.LogInformation($"File ({fileToDelete.Id}/{fileToDelete.InternalName}) was deleted");
        return RedirectToAction("Index");
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> Create(FuzzingTaskModel model)
    {
        model.CreateTime = DateTime.Now;
        try
        {
            if (!model.Fuzzer.IsNullOrEmpty())
            {
                // Add task to DB
                await _context.FuzzingTasks.AddAsync(model);
                await _context.SaveChangesAsync();
                _logger.LogInformation("Task added to DB");
                
                // Get shared storage creds
                SharedStorageModel storage = await _context.SharedStorage.FirstAsync();
                _logger.LogDebug("Shared storage creds is received");
                
                // Init task on shared storage
                ILogger staticLogger = LogHelper.CreateStaticLogger("SSHExecutor");
                await _context.UploadFileSettings.FindAsync(model.BuildId);
                _logger.LogInformation("Initializing a task...");
                bool result = await SSHExecutor.TaskInit(
                    new HostModel()
                    {
                        IpAddress = storage.IpAddress,
                        Password = storage.Password,
                        Username = storage.Username
                    },
                    model,
                    _configuration["NFSROOT"],
                    staticLogger);
                if (!result)
                {
                    throw new SshException("Can not init task on shared storage");
                }
                _logger.LogInformation("Task initialized");
            }
            else
            {
                throw new DbUpdateException("Invalid model");
            }
        }
        catch (Exception e)
        {
            _logger.LogError(e.Message);
            return View("Error",
                new ErrorViewModel()
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    ErrorMessage = e.Message
                });
        }
        
        return RedirectToAction("Index");
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> DeleteTask(int taskId)
    {
        ILogger staticLogger = LogHelper.CreateStaticLogger("SSHExecutor");
        _logger.LogDebug($"Deleting fuzzing task {taskId}");
        
        // Select task from DB
        FuzzingTaskModel? task = await _context.FuzzingTasks.FindAsync(taskId);
        if (task == null)
        {
            _logger.LogError($"Task with id {taskId} not found");
            return View("Error",
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        // Get shared storage creds
        SharedStorageModel storage = await _context.SharedStorage.FirstAsync();
        
        // Delete task from storage
        bool result = await SSHExecutor.DeleteTask(storage, task, _configuration["NFSROOT"], staticLogger);
        if (!result)
        {
            return View(
                "Error",
                new ErrorViewModel()
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    ErrorMessage = "Can not delete task from storage"
                });
        }
        
        // Delete task from DB
        _context.Remove(task);
        await _context.SaveChangesAsync();
        
        // ClusterConfigurationModel node = _context.ClusterConfiguration.ToList()[0];
        // ILogger staticLogger = LogHelper.CreateStaticLogger("SSHExecutor");
        // bool result = false;
        // if (task.Fuzzer == "AFL++")
        // {
        //     result = await SSHExecutor.DeleteTask(node, task, _configuration["NFSROOT"], "afl", staticLogger);
        // }
        // else if (task.Fuzzer == "libFuzzer")
        // {
        //     result = await SSHExecutor.DeleteTask(node, task, _configuration["NFSROOT"], "libfuzzer", staticLogger);
        // }
        //
        // if (!result)
        // {
        //     _logger.LogWarning("Can not delete task from storage");
        // }
        //
        // _context.FuzzingTasks.Remove(task);
        // await _context.SaveChangesAsync();
        // _logger.LogInformation($"Fuzzing task {taskId} was deleted");
        return RedirectToAction("Index");
    }

    [Authorize]
    [HttpGet]
    public async Task<IActionResult> GetTask(int taskId)
    {
        // Select task from DB
        FuzzingTaskModel? task = await _context.FuzzingTasks.FindAsync(taskId);
        if (task == null)
        {
            _logger.LogError($"Task with id {taskId} not found");
            return View("Error",
                new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    ErrorMessage = "Task with this id not found"
                });
        }

        // Resolve associated build
        await _context.UploadFileSettings.FindAsync(task.BuildId);

        // Add nodes to ViewBag
        List<ClusterConfigurationModel> nodes = _context.ClusterConfiguration.ToList();

Views/FuzzingLaunch/Index.cshtml
@model ApSafeFuzz.Models.FuzzingTaskModel
@{
    ViewData["Title"] = "Fuzzing launch";
}

<p>Number of <a asp-controller="FuzzingLaunch" asp-action="Upload">uploaded</a> builds: @ViewBag.buildsCount</p>
<br/>
<h1>Create fuzzing task</h1>
<form asp-controller="FuzzingLaunch" asp-action="Create" method="post">
    <input type="text" class="input-task" name="Name" placeholder="Task name" asp-for="Name" required="required"/><br/>
    <input type="text" class="input-task" name="Description" placeholder="Description" asp-for="Description"/><br/>
    <input type="radio" class="input-task" name="Fuzzer" id="libFuzzer" value="libFuzzer" asp-for="Fuzzer"/>
    <label for="libFuzzer">libFuzzer</label>
    <input type="radio" name="Fuzzer" id="AFL++" value="AFL++" asp-for="Fuzzer"/>
    <label for="AFL++">AFL++</label><br/>
    <input type="text" class="input-task" name="BuildId" placeholder="BuildId" asp-for="BuildId"/><br/>
    <input type="text" class="input-task" name="Environment" placeholder="Environment" asp-for="Environment"/><br/>
    <button class="btn btn-lg btn-primary btn-block input-task" type="submit">
        Submit
    </button>
</form>
<br/>

@if (ViewBag.fuzzingTasks.Count > 0)
{
    <h1 style="margin-top: 20px">Task list</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Action</th>
            <th>Id</th>
            <th>Name</th>
            <th>Fuzzer</th>
        </tr>
        </thead>
        <tbody>
        @foreach (FuzzingTaskModel task in ViewBag.fuzzingTasks)
        {
            <tr>
                <td>
                    <form asp-controller="FuzzingLaunch" asp-action="GetTask" asp-route-taskId="@task.Id" method="get">
                        <input type="hidden" name="taskId" value="@task.Id" />
                        <button type="submit">View</button>
                    </form>
                    <form asp-controller="FuzzingLaunch" asp-action="DeleteTask" asp-route-taskId="@task.Id" method="get">
                        <input type="hidden" name="taskId" value="@task.Id"/>
                        <button type="submit">Delete</button>
                    </form>
                </td>
                <td>@task.Id</td>
                <td>@task.Name</td>
                <td>@task.Fuzzer</td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <p>No fuzzing tasks</p>
}

@* <select id="selection"> *@
@*     <option value="option0"></option> *@
@*     <option value="option1">Вариант 1</option> *@
@*     <option value="option2">Вариант 2</option> *@
@* </select> *@
@* *@
@* <div id="input1" style="display: none;"> *@
@*     <p>Input 1</p> *@
@*     <input type="text" name="option1Field"> *@
@* </div> *@
@* *@
@* <div id="input2" style="display: none;"> *@
@*     <p>Input 2</p> *@
@*     <input type="text" name="option2Field"> *@
@* </div> *@
@* <script src="js/dropdown.js"></script> *@

Views/FuzzingLaunch/Task.cshtml
@using System.Reflection.Metadata.Ecma335
@model FuzzingTaskModel
@{
ViewData["Title"] = "Task details";
}

@{
    FuzzingTaskModel task = Model;
    UploadFileSettingsModel file = Model.UploadFileSettingsModel;
}
<form asp-controller="FuzzingLaunch" asp-action="DeleteTask" asp-route-taskId="@task.Id" method="get">
    <input type="hidden" name="taskId" value="@task.Id" />
    <button type="submit">Delete task</button>
</form>
<form asp-controller="FuzzingLaunch" asp-action="RunTask" asp-route-taskId="@task.Id" method="get">
    <input type="hidden" name="taskId" value="@task.Id" />
    @foreach (ClusterConfigurationModel node in ViewBag.nodes)
    {
        <input type="checkbox" name="selectedNodes" value="@node.Id"/>
        <label>@node.IpAddress</label>
    }
    <button type="submit">Run task</button>
</form>
<form method="get">
    <button type="submit">Stop task</button>
</form>

<h1>Task details</h1>
<p><strong>Id</strong>: @task.Id</p>
<p><strong>Name</strong>: @task.Name</p>
<p><strong>Status</strong>: @task.Status</p>
@{
    if (task.PID != null)
    {
        <p><strong>PID</strong>: @String.Join(", ", task.PID)</p>
    }
}
<p><strong>Description</strong>: @task.Description</p>
<p><strong>Create time</strong>: @task.CreateTime</p>
<p><strong>Fuzzer</strong>: @task.Fuzzer</p>
<p><strong>Environment</strong>: @task.Environment</p>

<h1>Build details</h1>
<p><strong>Id</strong>: @file.Id</p>
<p><strong>Upload name</strong>: @file.UploadName</p>
<p><strong>Upload time</strong>: @file.UploadTime</p>
<p><strong>Owner</strong>: @file.Owner</p>
<p><strong>Internal name</strong>: @file.InternalName</p>
<p><strong>File path</strong>: @file.FilePath</p>

Views/FuzzingLaunch/Upload.cshtml
@model List<UploadFileSettingsModel>
@{
    ViewData["Title"] = "Upload file";
}

<form enctype="multipart/form-data" method="post" asp-action="Upload" asp-controller="FuzzingLaunch">
    <input type="file" name="uploadedFile" /><br/>
    <input type="submit" value="Upload" />
</form>

@if (Model.Count > 0)
{
    <table class="table">
        <thead>
        <tr>
            <th>Action</th>
            <th>Id</th>
            <th>Owner</th>
            <th>Upload time</th>
            <th>Upload name</th>
        </tr>
        </thead>
        <tbody>
        @foreach (UploadFileSettingsModel item in Model)
        {
            <tr>
                <td>
                    <form asp-controller="FuzzingLaunch" asp-action="Delete" asp-route-fileId="@item.Id" method="get">
                        <input type="hidden" name="fileId" value="@item.Id"/>
                        <button type="submit">Delete</button>
                    </form>
                </td>
                <td>@item.Id</td>
                <td>@item.Owner</td>
                <td>@item.UploadTime</td>
                <td>@item.UploadName</td>
            </tr>
        }
        </tbody>
    </table>
}